spring:
  #thymeleaf
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  #h2
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/ahnShop
    username: sa
    password:

#mybatis
#mybatis:
#  configuration:
#    map-underscore-to-camel-case: true

logging:
  level:
    root: debug